call code --install-extension 2gua.rainbow-brackets
call code --install-extension abusaidm.html-snippets
call code --install-extension akamud.vscode-theme-onedark
call code --install-extension Angular.ng-template
call code --install-extension christian-kohler.npm-intellisense
call code --install-extension christian-kohler.path-intellisense
call code --install-extension CoenraadS.bracket-pair-colorizer
call code --install-extension donjayamanne.githistory
call code --install-extension EditorConfig.EditorConfig
call code --install-extension eg2.tslint
call code --install-extension eg2.vscode-npm-script
call code --install-extension IBM.output-colorizer
call code --install-extension ionutvmi.path-autocomplete
call code --install-extension johnpapa.Angular2
call code --install-extension ms-vscode.csharp
call code --install-extension ms-vscode.PowerShell
call code --install-extension ms-vscode.vs-keybindings
call code --install-extension PKief.material-icon-theme
call code --install-extension robinbentley.sass-indented
call code --install-extension shardulm94.trailing-spaces
call code --install-extension sourcegraph.javascript-typescript
call code --install-extension Tyriar.sort-lines
call code --install-extension Zignd.html-css-class-completion
